version: '2'
services:
  web:
    image: spacegoing/odoo_dev:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
      # Adding more ports only for debug usage
      - "8070:8070"
      # - "8071:8071" already been exposed by odoo
      # Dockerfile, don't use
      - "8072:8072"
      - "8073:8073"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./log:/var/log/odoo
      - ./.bin:/my_bin
      - ./addons/hdwolf/js:/usr/lib/python2.7/dist-packages/odoo/addons/point_of_sale/static/src/js
    # Must. otherwise will shadow Dockerfile's ENV PATH
    # which results there is no change to PATH
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/my_bin
    tty: true
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
